export const QUIZ_LIST_REQUEST = "QUIZ_LIST_REQUEST";
export const QUIZ_LIST_SUCCESS = "QUIZ_LIST_SUCCESS";
export const QUIZ_LIST_FAIL    = "QUIZ_LIST_FAIL";

export const QUIZ_DETAIL_REQUEST = "ADD_DETAIL_REQUEST";
export const QUIZ_DETAIL_SUCCESS = "ADD_DETAIL_SUCCESS";
export const QUIZ_DETAIL_FAIL    = "ADD_DETAIL_FAIL";
